#!/usr/bin/env bash
# Register anything-use MCP servers in ~/.codex/config.toml.
# Idempotent via marker comments: re-running replaces our managed block.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CFG="${CODEX_CONFIG:-$HOME/.codex/config.toml}"
BEGIN="# >>> anything-use BEGIN (managed) >>>"
END="# <<< anything-use END (managed) <<<"

mkdir -p "$(dirname "$CFG")"
[[ -f "$CFG" ]] || touch "$CFG"

# Strip any previous managed block (idempotent re-run).
if grep -qF "$BEGIN" "$CFG"; then
  awk -v b="$BEGIN" -v e="$END" '
    $0==b {skip=1; next}
    $0==e {skip=0; next}
    !skip {print}
  ' "$CFG" > "$CFG.tmp" && mv "$CFG.tmp" "$CFG"
fi

# Build new block.
{
  echo
  echo "$BEGIN"
  echo "# Generated by anything-use scripts/install-codex.sh"
  echo "# Repo: $ROOT"
  echo

  if [[ -x "$ROOT/servers/browser/run.sh" ]]; then
    cat <<EOF
[mcp_servers.browser]
command = "bash"
args = ["$ROOT/servers/browser/run.sh"]
startup_timeout_sec = 60

EOF
  fi

  cat <<EOF
[mcp_servers.mobile]
command = "npx"
args = ["-y", "@mobilenext/mobile-mcp@latest"]
env = { MOBILEMCP_DISABLE_TELEMETRY = "1" }
startup_timeout_sec = 60

EOF

  if [[ -f "$ROOT/servers/computer/wrapper/mcp_server.py" ]]; then
    cat <<EOF
[mcp_servers.computer]
command = "python3"
args = ["$ROOT/servers/computer/wrapper/mcp_server.py"]
startup_timeout_sec = 120

EOF
  fi

  echo "$END"
} >> "$CFG"

echo "Wrote MCP block to $CFG"
echo "Inspect with: sed -n '/$BEGIN/,/$END/p' \"$CFG\""
